VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Denomination"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Rs500 As Integer
Public Rs100 As Integer
Public Rs50 As Integer
Public Rs20 As Integer
Public Rs10 As Integer
Public Rs5 As Integer
Public Rs2 As Integer
Public Rs1 As Integer
Public Coins As Integer


