Attribute VB_Name = "basBankAcc"
Option Explicit
Public Const wis_BankHeadOffSet = 1000
Enum wisBankHeads
  wis_BankHead = 1000
  wis_BankLoanHead = 2000
  wis_AdvanceHead = 3000
  wis_InvestmentHead = 4000
  wis_IncomeHead = 5000
  wis_ExpenditureHead = 6000
  wis_TradingIncomeHead = 7000
  wis_TradingExpenditureHead = 8000
  wis_ReserveFundHead = 9000
  wis_ShareCapitalHead = 10000
  wis_GovtLoanSubsidyHead = 11000
  wis_AssetHead = 12000
  wis_PaymentHead = 13000
  wis_RepaymentHead = 14000
  
  'Particularly for Hiewpadasalagi
  'Particularly for Hirepadasalagi
  wis_MemberDeposits = 20000
  
End Enum
